services:
  db:
    image: postgres:15
    container_name: system_monitoring_db
    environment:
      POSTGRES_USER: monitoring_user # database username
      POSTGRES_PASSWORD: mntusr-pass-3517 # database password
      POSTGRES_DB: monitoring_db # database name
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: